include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - riverpod_lint
  exclude:
    - "**/*.g.dart"
    - "test/generated_migrations/**"

linter:
  rules:
    prefer_const_constructors: true
    prefer_final_locals: true
